### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alvaro-garcia-solano** [tetreum/xupopter#1]
Good morning,

i have installed the project via composer like it´s mentioned in the README file.

i have imported the code into a Netbeans PHP project but i don´t manage to run the script.  I suspect i must create a config.php file, is this right?  If I run the script correctly will i see results on the console or will the crawled data be saved to a file?

Sorry for the inconvenience and looking forward to try the script.

Thanks beforehand.

**Comment by tetreum** [comment]
Maybe the readme file it's not quite clear, but in https://github.com/tetreum/xupopter#ejemplo-de-uso i show a `config.php` example.
This script will fire a callback on each crawled entry, so you can do whatever you want, like printing/saving it on a db.

**Comment by alvaro-garcia-solano** [comment]
I have to create the bootstrap.php, conf.php and cron.php right? Where do I place them? In order to run the script i must run App.php?

Thanks for the quick response.

**Comment by tetreum** [comment]
On the root, should look like:
```
App/
test/
composer.json
conf.php
cron.php
bootstrap.php
```

If you're making the cron, then you should run `php cron.php`

My setup runs a daily cron that saves the results in a db and then i have a simple frontend to see the results:
![http://i.imgur.com/rMsqpWy.png](http://i.imgur.com/rMsqpWy.png)

**Comment by alvaro-garcia-solano** [comment]
Ok I manage to run it now.  I´m getting exceptions, do I need to update the code for it work or is it supposed to work without any changes?

**Comment by tetreum** [comment]
Dunno, post the thrown exceptions here.

**Comment by alvaro-garcia-solano** [comment]
Fatal error: Uncaught exception 'Xupopter\System\ProviderException' with message 'invalid object integrity: title:string' in F:\PC-1\xamp\htdocs\pruebas\xup3\vendor\tetreum\xupopter\App\System\Provider.php on line 162
( ! ) Xupopter\System\ProviderException: invalid object integrity: title:string in F:\PC-1\xamp\htdocs\pruebas\xup3\vendor\tetreum\xupopter\App\System\Provider.php on line 162
Call Stack
#	Time	Memory	Function	Location
1	0.0010	132184	{main}( )	...\cron.php:0
2	0.0040	229992	Xupopter\System\App::runProvider( )	...\cron.php:14
3	0.0050	312280	Xupopter\System\Provider->start( )	...\App.php:70
4	0.0050	312512	Xupopter\Providers\Habitaclia->crawl( )	...\Provider.php:40
5	1.6011	1271832	Xupopter\System\Provider->sendToDB( )	...\Habitaclia.php:21
6	1.6011	1271928	Xupopter\System\Provider->checkIntegrity( )	...\Provider.php:133

**Comment by tetreum** [comment]
Seems like Habitaclia has changed it's design, you can try excluding it from the crawl process or fixing it ofc.

**Comment by alvaro-garcia-solano** [comment]
For Habitaclia the title it´s not working, Pisos seems to be OK, Idealista I get errors and Fotocasa does´nt show up.
Output;
https://www.habitaclia.com/comprar-casa-palacio_modernista_en_venta_sant_gervasi_bonanova-barcelona-i10578000000035.htm - 14000000€ - 
https://www.habitaclia.com/comprar-chalet-espectacular_palacio_con_piscina_sarria-barcelona-i5162002600034.htm - 14000000€ - 
https://www.habitaclia.com/comprar-casa-emblematica_modernista_sant_gervasi_bonanova-barcelona-i4737002476175.htm - 14000000€ - 
https://www.habitaclia.com/comprar-apartamento-venta_de_s_turisticos_raval-barcelona-i3955002424371.htm - 12500000€ - 
https://www.habitaclia.com/comprar-casa-pearson_pedralbes-barcelona-i6143002681725.htm - 11000000€ - 
https://www.habitaclia.com/comprar-duplex-pedrera_pg_de_gracia_dreta_de_l_eixample-barcelona-i586002481151.htm - 10500000€ - 
https://www.habitaclia.com/comprar-torre-venta_pedralbes-barcelona-i885002460575.htm - 10000000€ - 
https://www.habitaclia.com/comprar-casa-inmejorables_vistas_en_pearson_pedralbes-barcelona-i4017002552257.htm - 10000000€ - 
https://www.habitaclia.com/comprar-casa-con_jardin_y_piscina_en_avenida_pearson_pedralbes-barcelona-i8166001784697.htm - 10000000€ - 
https://www.habitaclia.com/comprar-casa-de_lujo_espectacular_con_piscina_sant_gervasi_bonanova-barcelona-i3025001633750.htm - 8500000€ - 
https://www.habitaclia.com/comprar-casa-impresionante_finca_de_diseno_en_avenida_tibidabo_sant_gervasi_bonanova-barcelona-i8166001784631.htm - 8500000€ - 
https://www.habitaclia.com/comprar-casa-impresionante_en_venta_en_sant_gervasi_barce_sant_gervasi_bonanova-barcelona-i2652001520753.htm - 8500000€ - 
https://www.habitaclia.com/comprar-casa-excepcional_en_zona_alta_sant_gervasi_bonanova-barcelona-i1854001774325.htm - 8500000€ - 
https://www.habitaclia.com/comprar-casa-lujosa_y_espectacular_sant_gervasi_bonanova-barcelona-i3901002307185.htm - 8000000€ - 
https://www.habitaclia.com/comprar-chalet-con_piscina_y_vistas_a_la_ciudad_sant_gervasi_bonanova-barcelona-i5162002599818.htm - 8000000€ - 
https://www.pisos.com/comprar/chalet-pedralbes-68378887050_103800/ - 15500000€ - Chalet en venta en calle , Pedralbes
https://www.pisos.com/comprar/casa_unifamiliar-sant_gervasi_bonanova08022-74248632635_101600/ - 14000000€ - Casa unifamiliar en venta en Sant Gervasi I La Bonanova
https://www.pisos.com/comprar/casa-sant_gervasi_bonanova08022-543146304_399900/ - 14000000€ - Casa en venta en Sant Gervasi - Bonanova
https://www.pisos.com/comprar/piso-la_dreta_de_eixample08008-71739379214_106700/ - 10500000€ - Piso en venta en Eixample
https://www.pisos.com/comprar/casa-pedralbes-74172785881_109100/ - 10000000€ - Casa en venta en Vistas Exclusivas de Barcelona
https://www.pisos.com/comprar/casa-sant_gervasi_bonanova08035-75053617099_108900/ - 8500000€ - Casa en venta en calle Llu?S Muntadas, nº 12
https://www.pisos.com/comprar/piso-el_raval08001-945856909132740_109800/ - 8200000€ - Piso en venta en calle Sant Rafael, nº 18
https://www.pisos.com/comprar/casa-sant_gervasi_bonanova08035-66756882827_101600/ - 8000000€ - Casa en venta en Sarrià - Sant Gervasi - Sant Gervasi I La Bonanova
https://www.pisos.com/comprar/piso-sant_pere_santa_caterina_i_la_ribera08003-945856909123548_109700/ - 7500000€ - Piso en venta en calle Giriti
https://www.pisos.com/comprar/casa_unifamiliar-sant_gervasi_bonanova08035-61766504488_101600/ - 7000000€ - Casa unifamiliar en venta en Sarrià - Sant Gervasi - Tibidabo
https://www.pisos.com/comprar/casa-pedralbes-75059582870_101600/ - 6900000€ - Casa en venta en Pedralbes
https://www.pisos.com/comprar/casa-pedralbes-75072314725_108900/ - 6900000€ - Casa en venta en Sector Pedralbes, nº 1
https://www.pisos.com/comprar/casa-pedralbes-74196895764_101600/ - 6900000€ - Casa en venta en Pedralbes
https://www.pisos.com/comprar/casa-pedralbes-73419575792_100100/ - 5950000€ - Casa en venta en Avenida de Pearson
https://www.pisos.com/comprar/casa-pedralbes-50920314814_109100/ - 5950000€ - Casa en venta en Junto Avenida Pearson
https://www.pisos.com/comprar/casa-pedralbes-75000595841_108900/ - 5500000€ - Casa en venta en Avenida Avenida Pearson, nº 35
https://www.pisos.com/comprar/piso-sant_gervasi_galvany08021-73414026498_101600/ - 5300000€ - Piso en venta en Turó Park
https://www.pisos.com/comprar/piso-sant_gervasi_galvany08021-74215915554_104400/ - 5300000€ - Piso en venta en Sant Gervasi - Galvany
https://www.pisos.com/comprar/casa-sant_gervasi_bonanova08017-65892856060_101600/ - 5300000€ - Casa en venta en Sarrià - Sant Gervasi - Sant Gervasi I La Bonanova
https://www.pisos.com/comprar/piso-antiga_esquerra_de_eixample08011-945856909167506_109700/ - 5150000€ - Piso en venta en Avenida Comte D´Urgell
https://www.pisos.com/comprar/casa-pedralbes-58088434_148700/ - 5000000€ - Casa en venta en Pedralbes
https://www.pisos.com/comprar/casa-sant_gervasi_bonanova08017-638034296_438500/ - 4500000€ - Casa en venta en calle Planella
https://www.pisos.com/comprar/piso-el_gotic08002-945856909125943_109700/ - 4350000€ - Piso en venta en calle Ramblas
https://www.pisos.com/comprar/piso-el_gotic08002-70926283094_108100/ - 4350000€ - Piso en venta en Ciutat Vella
https://www.pisos.com/comprar/casa-sant_gervasi_bonanova08017-70851647312_109100/ - 3950000€ - Casa en venta en Iradier- La Bonanova
https://www.pisos.com/comprar/casa-sarria_sant_gervasi_sarria08017-74192981197_104400/ - 3950000€ - Casa en venta en Sarrià
https://www.pisos.com/comprar/piso-sants_montjuic_hostafrancs-945856909106463_109700/ - 3850000€ - Piso en venta en calle Leiva
https://www.pisos.com/comprar/piso-sant_gervasi_galvany08021-63349850625_109100/ - 3700000€ - Piso en venta en Junto A Plaza San Gregorio Taumaturgo
https://www.pisos.com/comprar/piso-la_dreta_de_eixample08008-74188254728_101600/ - 3600000€ - Piso en venta en Eixample - Dreta de Leixample

Is there any posibility for you commiting the latest version?

**Comment by tetreum** [comment]
Habitaclia & Fotocasa crawlers updated
I didn't have any problem with the others
